apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-canary
  namespace: argocd
spec:
  spec:
  source:
    repoURL: https://github.com/nareshmaran/bookinfo-gitops
    targetRevision: main
    path: bookinfo-helm
    helm:
      valueFiles:
        - values.yaml
